networks:
  default:
    name: cumulus-api_default
    # name: water-api_default
    # name: instrumentation-api_default

services:
  airflowdb:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'airflow' ]
      interval: 5s
      retries: 5
    # ports:
    #   - '5432:5432'

  airflow_init:
    env_file:
      - ./airflow.env
    image: apache/airflow:2.1.4-python3.8
    depends_on:
      - airflowdb
    entrypoint: >
      /bin/sh -c "
      /entrypoint db reset -y;
      /entrypoint db init;
      /entrypoint users create --role Admin --username airflow --email airflow@airflow.com --firstname airflow --lastname airflow --password airflow;
      exit 0;
      "
  airflow_scheduler:
    env_file:
      - ./airflow.env
    image: apache/airflow:2.1.4-python3.8
    # depends_on:
    #   - airflow_init
    depends_on:
      airflowdb:
        condition: service_healthy
      airflow-init:
        condition: service_started
    restart: always
    # command: scheduler
    entrypoint: >
      /bin/sh -c "sleep 15 && airflow scheduler"
    volumes:
      - ./logs:/opt/airflow/logs
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
  airflow_ui:
    env_file:
      - ./airflow.env
    image: apache/airflow:2.1.4-python3.8
    depends_on:
      - airflow_init
      - airflow_scheduler
    restart: always
    # environment:
    ports:
      - '8000:8080'
    command: webserver
