PE_CONVERSIONS = {
    #
    # May be modified by SHEFPARM file
    #
    # Numeric values are SI->English unit conversion factors (units specified in manual)
    #
    # Note tha PE code PL was changed from English unit of in-hg (as specified in manual)
    # to mb (as specified in SHEFPARM comment at the top of this script). SI unit not changed.
    #
    "AD": (1.0, None, None),
    "AF": (1.0, "n/a", "n/a"),
    "AG": (1.0, "%", "%"),
    "AM": (1.0, "n/a", "n/a"),
    "AT": (1.0, "n/a", "n/a"),
    "AU": (1.0, "n/a", "n/a"),
    "AW": (1.0, "n/a", "n/a"),
    "BA": (0.0393701, "in", "mm"),
    "BB": (0.0393701, "in", "mm"),
    "BC": (0.0393701, "in", "mm"),
    "BD": (-1.0, "F", "C"),
    "BE": (0.0393701, "in", "mm"),
    "BF": (0.0393701, "in", "mm"),
    "BG": (1.0, "%", "%"),
    "BH": (0.0393701, "in", "mm"),
    "BI": (0.0393701, "in", "mm"),
    "BJ": (0.0393701, "in", "mm"),
    "BK": (0.0393701, "in", "mm"),
    "BL": (0.0393701, "in", "mm"),
    "BM": (0.0393701, "in", "mm"),
    "BN": (0.0393701, "in", "mm"),
    "BO": (0.0393701, "in", "mm"),
    "BP": (0.0393701, "in", "mm"),
    "BQ": (0.0393701, "in", "mm"),
    "CA": (0.0393701, "in", "mm"),
    "CB": (0.0393701, "in", "mm"),
    "CC": (0.0393701, "in", "mm"),
    "CD": (0.0393701, "in", "mm"),
    "CE": (0.0393701, "in", "mm"),
    "CF": (0.0393701, "in", "mm"),
    "CG": (0.0393701, "in", "mm"),
    "CH": (0.0393701, "in", "mm"),
    "CI": (0.0393701, "in", "mm"),
    "CJ": (0.0393701, "in", "mm"),
    "CK": (0.0393701, "in", "mm"),
    "CL": (-1.0, "F", "C"),
    "CM": (-1.0, "F", "C"),
    "CN": (1.0, "%", "%"),
    "CO": (1.0, "n/a", "n/a"),
    "CP": (0.0393701, "in", "mm"),
    "CQ": (0.0393701, "in", "mm"),
    "CR": (0.0393701, "in", "mm"),
    "CS": (0.0393701, "in", "mm"),
    "CT": (1.0, "unit", "unit"),
    "CU": (-1.0, "F", "C"),
    "CV": (-1.0, "F", "C"),
    "CW": (0.0393701, "in", "mm"),
    "CX": (0.0393701, "in", "mm"),
    "CY": (0.0393701, "in", "mm"),
    "CZ": (1.0, "n/a", "n/a"),
    "EA": (0.0393701, "in", "mm"),
    "ED": (0.0393701, "in", "mm"),
    "EM": (0.0393701, "in", "mm"),
    "EP": (0.0393701, "in", "mm"),
    "ER": (0.0393701, "in", "mm"),
    "ET": (0.0393701, "in", "mm"),
    "EV": (0.0393701, "in", "mm"),
    "FA": (1.0, "unit", "unit"),
    "FB": (1.0, "unit", "unit"),
    "FC": (1.0, "unit", "unit"),
    "FE": (1.0, "unit", "unit"),
    "FK": (1.0, "unit", "unit"),
    "FL": (1.0, "n/a", "n/a"),
    "FP": (1.0, "unit", "unit"),
    "FS": (1.0, "unit", "unit"),
    "FT": (1.0, "n/a", "n/a"),
    "FZ": (1.0, "unit", "unit"),
    "GC": (1.0, "unit", "unit"),
    "GD": (0.3937008, "in", "cm"),
    "GL": (1.0, "%", "%"),
    "GP": (0.3937008, "in", "cm"),
    "GR": (1.0, "n/a", "n/a"),
    "GS": (1.0, "n/a", "n/a"),
    "GT": (0.3937008, "in", "cm"),
    "GW": (0.3937008, "in", "cm"),
    "HA": (3.2808399, "ft", "m"),
    "HB": (3.2808399, "ft", "m"),
    "HC": (3.2808399, "ft", "m"),
    "HD": (3.2808399, "ft", "m"),
    "HE": (3.2808399, "ft", "m"),
    "HF": (3.2808399, "ft", "m"),
    "HG": (3.2808399, "ft", "m"),
    "HH": (3.2808399, "ft", "m"),
    "HI": (1.0, "n/a", "n/a"),
    "HJ": (3.2808399, "ft", "m"),
    "HK": (3.2808399, "ft", "m"),
    "HL": (3.2808399, "ft", "m"),
    "HM": (3.2808399, "ft", "m"),
    "HO": (3.2808399, "ft", "m"),
    "HP": (3.2808399, "ft", "m"),
    "HQ": (1.0, "n/a", "n/a"),
    "HR": (3.2808399, "ft", "m"),
    "HS": (3.2808399, "ft", "m"),
    "HT": (3.2808399, "ft", "m"),
    "HU": (3.2808399, "ft", "m"),
    "HV": (0.0393701, "in", "mm"),
    "HW": (3.2808399, "ft", "m"),
    "HZ": (3.2808399, "ft", "m"),
    "IC": (1.0, "%", "%"),
    "IE": (0.6213712, "mi", "km"),
    "IO": (3.2808399, "ft", "m"),
    "IR": (1.0, "n/a", "n/a"),
    "IT": (0.3937008, "in", "cm"),
    "LA": (247.10541, "acre * 1000", "km2"),
    "LC": (0.8107131, "kaf", "mcm"),
    "LS": (0.8107131, "kaf", "mcm"),
    "MD": (1.0, "n/a", "n/a"),
    "MI": (1.0, "n/a", "n/a"),
    "ML": (0.3937008, "in", "cm"),
    "MM": (1.0, "%", "%"),
    "MN": (1.0, "n/a", "n/a"),
    "MS": (1.0, "n/a", "n/a"),
    "MT": (-1.0, "F", "C"),
    "MU": (0.3937008, "in", "cm"),
    "MV": (1.0, "n/a", "n/a"),
    "MW": (1.0, "%", "%"),
    "NC": (1.0, "n/a", "n/a"),
    "NG": (3.2808399, "ft", "m"),
    "NL": (1.0, "unit", "unit"),
    "NN": (1.0, "unit", "unit"),
    "NO": (1.0, "n/a", "n/a"),
    "NS": (1.0, "unit", "unit"),
    "PA": (0.295297, "in-hg", "kPa"),
    "PC": (0.0393701, "in", "mm"),
    "PD": (0.295297, "in-hg", "kPa"),
    "PE": (1.0, "n/a", "n/a"),
    "PJ": (0.0393701, "in", "mm"),
    "PL": (10.0, "mb", "KPa"),
    "PM": (1.0, "n/a", "n/a"),
    "PN": (0.0393701, "in", "mm"),
    "PP": (0.0393701, "in", "mm"),
    "PR": (0.0393701, "in", "mm"),
    "PT": (1.0, "n/a", "n/a"),
    "PY": (0.0393701, "in", "mm"),
    "QA": (0.0353147, "kcfs", "cms"),
    "QB": (0.0393701, "in", "mm"),
    "QC": (0.8107131, "kaf", "mcm"),
    "QD": (0.0353147, "kcfs", "cms"),
    "QE": (1.0, "%", "%"),
    "QF": (0.6213712, "mi", "km"),
    "QG": (0.0353147, "kcfs", "cms"),
    "QI": (0.0353147, "kcfs", "cms"),
    "QL": (0.0353147, "kcfs", "cms"),
    "QM": (0.0353147, "kcfs", "cms"),
    "QP": (0.0353147, "kcfs", "cms"),
    "QR": (0.0353147, "kcfs", "cms"),
    "QS": (0.0353147, "kcfs", "cms"),
    "QT": (0.0353147, "kcfs", "cms"),
    "QU": (0.0353147, "kcfs", "cms"),
    "QV": (0.8107131, "kaf", "mcm"),
    "QZ": (1.0, "n/a", "n/a"),
    "RA": (1.0, "%", "%"),
    "RI": (1.0, "langley", "langley"),
    "RN": (1.0, "W/m2", "W/m2"),
    "RP": (1.0, "%", "%"),
    "RT": (1.0, "hr", "hr"),
    "RW": (1.0, "W/m2", "W/m2"),
    "SA": (1.0, "%", "%"),
    "SB": (0.0393701, "in", "mm"),
    "SD": (0.3937008, "in", "cm"),
    "SE": (-1.0, "F", "C"),
    "SF": (0.3937008, "in", "cm"),
    "SI": (0.3937008, "in", "cm"),
    "SL": (0.0032808, "ft * 1000", "m"),
    "SM": (0.0393701, "in", "mm"),
    "SP": (0.0393701, "in", "mm"),
    "SR": (1.0, "n/a", "n/a"),
    "SS": (1.0, "n/a", "n/a"),
    "ST": (1.0, "n/a", "n/a"),
    "SU": (0.0393701, "in", "mm"),
    "SW": (0.0393701, "in", "mm"),
    "TA": (-1.0, "F", "C"),
    "TB": (1.0, "n/a", "n/a"),
    "TC": (-1.0, "F", "C"),
    "TD": (-1.0, "F", "C"),
    "TE": (1.0, "n/a", "n/a"),
    "TF": (-1.0, "F", "C"),
    "TH": (-1.0, "F", "C"),
    "TJ": (-1.0, "F", "C"),
    "TM": (-1.0, "F", "C"),
    "TP": (-1.0, "F", "C"),
    "TR": (-1.0, "F", "C"),
    "TS": (-1.0, "F", "C"),
    "TV": (1.0, "n/a", "n/a"),
    "TW": (-1.0, "F", "C"),
    "TZ": (-1.0, "F", "C"),
    "UC": (0.6213712, "mi", "km"),
    "UD": (1.0, "deg", "deg"),
    "UE": (1.0, "deg", "deg"),
    "UG": (2.2369363, "mph", "m/s"),
    "UH": (1.0, "deg * 10", "deg * 10"),
    "UL": (0.6213712, "mi", "km"),
    "UP": (1.0, "mph", "mph"),
    "UQ": (1.0, "n/a", "n/a"),
    "UR": (1.0, "deg * 10", "deg * 10"),
    "US": (2.2369363, "mph", "m/s"),
    "UT": (1.0, "min", "min"),
    "VB": (1.0, "volt", "volt"),
    "VC": (1.0, "MW", "MW"),
    "VE": (1.0, "MWh", "MWh"),
    "VG": (1.0, "MW", "MW"),
    "VH": (1.0, "hr", "hr"),
    "VJ": (1.0, "MWh", "MWh"),
    "VK": (1.0, "MW * duration", "MW * duration"),
    "VL": (1.0, "MW * duration", "MW * duration"),
    "VM": (1.0, "MW * duration", "MW * duration"),
    "VP": (1.0, "MW", "MW"),
    "VQ": (1.0, "MWh", "MWh"),
    "VR": (1.0, "MW * duration", "MW * duration"),
    "VS": (1.0, "MWh", "MWh"),
    "VT": (1.0, "MW", "MW"),
    "VU": (1.0, "n/a", "n/a"),
    "VW": (1.0, "MW", "MW"),
    "WA": (1.0, "ppm", "mg/l"),
    "WC": (1.0, "umho/cm", "umho/cm"),
    "WD": (0.3937008, "in", "cm"),
    "WG": (0.0393701, "in", "mm"),
    "WH": (1.0, "ppm", "mg/l"),
    "WL": (1.0, "ppm", "mg/l"),
    "WO": (1.0, "ppm", "mg/l"),
    "WP": (1.0, "su (pH)", "su (pH)"),
    "WS": (1.0, "ppm * 1000", "ppm * 1000"),
    "WT": (1.0, "jtu", "jtu"),
    "WV": (3.2808399, "ft", "m"),
    "WX": (1.0, "%", "%"),
    "WY": (1.0, "ppm / 1000", "ug/l"),
    "XC": (1.0, "% / 10", "% / 10"),
    "XG": (1.0, "unit", "unit"),
    "XL": (1.0, "unit", "unit"),
    "XP": (1.0, "n/a", "n/a"),
    "XR": (1.0, "%", "%"),
    "XU": (2.2883564, "gm/ft3", "gm/m3"),
    "XV": (0.6213712, "mi", "km"),
    "XW": (1.0, "n/a", "n/a"),
    "YA": (1.0, "unit", "unit"),
    "YC": (1.0, "unit", "unit"),
    "YF": (1.0, "W", "W"),
    "YI": (1.0, "n/a", "n/a"),
    "YP": (1.0, "n/a", "n/a"),
    "YR": (1.0, "W", "W"),
    "YS": (1.0, "unit", "unit"),
    "YT": (1.0, "unit", "unit"),
    "YV": (1.0, "volt", "volt"),
    "YY": (1.0, "n/a", "n/a"),
}


SEND_CODES = {
    #
    # May be modified by SHEFPARM file
    #
    # Boolean values are whether value is at (or ends at) 0700 local time prior to time stamp
    #
    "AD": ("ADZZZZZ", False),
    "AT": ("ATD", False),
    "AU": ("AUD", False),
    "AW": ("AWD", False),
    "EA": ("EAD", False),
    "EM": ("EMD", False),
    "EP": ("EPD", False),
    "ER": ("ERD", False),
    "ET": ("ETD", False),
    "EV": ("EVD", False),
    "HN": ("HGIRZNZ", False),
    "HX": ("HGIRZXZ", False),
    "HY": ("HGIRZZZ", True),
    "LC": ("LCD", False),
    "PF": ("PPTCF", False),
    "PY": ("PPDRZZZ", True),
    "PP": ("PPD", False),
    "PR": ("PRD", False),
    "QC": ("QCD", False),
    "QN": ("QRIRZNZ", False),
    "QX": ("QRIRZXZ", False),
    "QY": ("QRIRZZZ", True),
    "SF": ("SFD", False),
    "TN": ("TAIRZNZ", False),
    "QV": ("QVZ", False),
    "RI": ("RID", False),
    "RP": ("RPD", False),
    "RT": ("RTD", False),
    "TC": ("TCS", False),
    "TF": ("TFS", False),
    "TH": ("THS", False),
    "TX": ("TAIRZXZ", False),
    "UC": ("UCD", False),
    "UL": ("ULD", False),
    "XG": ("XGJ", False),
    "XP": ("XPQ", False),
}

DURATION_CODES = {
    #
    # May be modified by SHEFPARM file
    #
    # numeric values are simply numeric equivalent codes
    #
    "I": 0,
    "U": 1,
    "E": 5,
    "G": 10,
    "C": 15,
    "J": 30,
    "H": 1001,
    "B": 1002,
    "T": 1003,
    "F": 1004,
    "Q": 1006,
    "A": 1008,
    "K": 1012,
    "L": 1018,
    "D": 2001,
    "W": 2007,
    "N": 2015,
    "M": 3001,
    "Y": 4001,
    "Z": 5000,
    "S": 5001,
    "R": 5002,
    "V": 5003,
    "P": 5004,
    "X": 5005,
}

TS_CODES = set(
    (
        #
        # May be modified by SHEFPARM file
        #
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "1A",
        "1B",
        "1C",
        "1D",
        "1F",
        "1G",
        "1M",
        "1P",
        "1R",
        "1S",
        "1T",
        "1V",
        "1W",
        "1X",
        "1Z",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "2A",
        "2B",
        "2C",
        "2D",
        "2F",
        "2G",
        "2M",
        "2P",
        "2R",
        "2S",
        "2T",
        "2V",
        "2W",
        "2X",
        "2Z",
        "32",
        "33",
        "34",
        "35",
        "36",
        "37",
        "38",
        "39",
        "3A",
        "3B",
        "3C",
        "3D",
        "3F",
        "3G",
        "3M",
        "3P",
        "3R",
        "3S",
        "3T",
        "3V",
        "3W",
        "3X",
        "3Z",
        "42",
        "43",
        "44",
        "45",
        "46",
        "47",
        "48",
        "49",
        "4A",
        "4B",
        "4C",
        "4D",
        "4F",
        "4G",
        "4M",
        "4P",
        "4R",
        "4S",
        "4T",
        "4V",
        "4W",
        "4X",
        "4Z",
        "52",
        "53",
        "54",
        "55",
        "56",
        "57",
        "58",
        "59",
        "5A",
        "5B",
        "5C",
        "5D",
        "5F",
        "5G",
        "5M",
        "5P",
        "5R",
        "5S",
        "5T",
        "5V",
        "5W",
        "5X",
        "5Z",
        "62",
        "63",
        "64",
        "65",
        "66",
        "67",
        "68",
        "69",
        "6A",
        "6B",
        "6C",
        "6D",
        "6F",
        "6G",
        "6M",
        "6P",
        "6R",
        "6S",
        "6T",
        "6V",
        "6W",
        "6X",
        "6Z",
        "72",
        "73",
        "74",
        "75",
        "76",
        "77",
        "78",
        "79",
        "7A",
        "7B",
        "7C",
        "7D",
        "7F",
        "7G",
        "7M",
        "7P",
        "7R",
        "7S",
        "7T",
        "7V",
        "7W",
        "7X",
        "7Z",
        "82",
        "83",
        "84",
        "85",
        "86",
        "87",
        "88",
        "89",
        "8A",
        "8B",
        "8C",
        "8D",
        "8F",
        "8G",
        "8M",
        "8P",
        "8R",
        "8S",
        "8T",
        "8V",
        "8W",
        "8X",
        "8Z",
        "92",
        "93",
        "94",
        "95",
        "96",
        "97",
        "98",
        "99",
        "9A",
        "9B",
        "9C",
        "9D",
        "9F",
        "9G",
        "9M",
        "9P",
        "9R",
        "9S",
        "9T",
        "9V",
        "9W",
        "9X",
        "9Z",
        "C1",
        "C2",
        "C3",
        "C4",
        "C5",
        "C6",
        "C7",
        "C8",
        "C9",
        "CA",
        "CB",
        "CC",
        "CD",
        "CE",
        "CF",
        "CG",
        "CH",
        "CI",
        "CJ",
        "CK",
        "CL",
        "CM",
        "CN",
        "CO",
        "CP",
        "CQ",
        "CR",
        "CS",
        "CT",
        "CU",
        "CV",
        "CW",
        "CX",
        "CY",
        "CZ",
        "FA",
        "FB",
        "FC",
        "FD",
        "FE",
        "FF",
        "FG",
        "FL",
        "FM",
        "FN",
        "FP",
        "FQ",
        "FR",
        "FU",
        "FV",
        "FW",
        "FX",
        "FZ",
        "HA",
        "HB",
        "HC",
        "HD",
        "HE",
        "HF",
        "HG",
        "HH",
        "HI",
        "HJ",
        "HK",
        "HL",
        "HM",
        "HN",
        "HO",
        "HP",
        "HQ",
        "HR",
        "HS",
        "HT",
        "HU",
        "HV",
        "HW",
        "HX",
        "HY",
        "HZ",
        "MA",
        "MC",
        "MH",
        "MK",
        "MS",
        "MT",
        "MW",
        "P1",
        "P2",
        "P3",
        "PA",
        "PB",
        "PC",
        "PD",
        "PE",
        "PF",
        "PG",
        "PH",
        "PI",
        "PJ",
        "PK",
        "PL",
        "PM",
        "PN",
        "PO",
        "PP",
        "PQ",
        "PR",
        "PS",
        "PT",
        "PU",
        "PV",
        "PW",
        "PX",
        "PY",
        "PZ",
        "R2",
        "R3",
        "R4",
        "R5",
        "R6",
        "R7",
        "R8",
        "R9",
        "RA",
        "RB",
        "RC",
        "RD",
        "RF",
        "RG",
        "RM",
        "RP",
        "RR",
        "RS",
        "RT",
        "RV",
        "RW",
        "RX",
        "RZ",
        "ZZ",
    )
)

EXTREMUM_CODES = set(
    (
        #
        # May be modified by SHEFPARM file
        #
        "D",  # Minimum of record
        "E",  # Minimum of year (calendar)
        "F",  # Minimum of month
        "G",  # Minimum of week
        "H",  # Minimum of day
        "I",  # Minimum of 1 hour
        "J",  # Minimum of 3 hours
        "K",  # Minimum of 6 hours
        "L",  # Minimum of 12 hours
        "M",  # Minimum of 18 hours
        "N",  # Maximum of record
        "P",  # Maximum of year (calendar)
        "R",  # Maximum of month
        "S",  # Maximum of week
        "T",  # Maximum of day
        "U",  # Maximum of 1 hour
        "V",  # Maximum of 3 hours
        "W",  # Maximum of 6 hours
        "X",  # Maximum of 12 hours
        "Y",  # Maximum of 18 hours
        "Z",  # Null character (filler)
    )
)

PROBABILITY_CODES = {
    #
    # May be modified by SHEFPARM file
    #
    # ABS of numeric values are probability of non-exceedence. Not sure why M and Z have negative values
    #
    "A": 0.002,
    "B": 0.004,
    "C": 0.01,
    "D": 0.02,
    "E": 0.04,
    "F": 0.05,
    "1": 0.1,
    "2": 0.2,
    "G": 0.25,
    "3": 0.3,
    "4": 0.4,
    "5": 0.5,
    "6": 0.6,
    "7": 0.7,
    "H": 0.75,
    "8": 0.8,
    "9": 0.9,
    "T": 0.95,
    "U": 0.96,
    "V": 0.98,
    "W": 0.99,
    "X": 0.996,
    "Y": 0.998,
    "J": 0.0013,
    "K": 0.0228,
    "L": 0.1587,
    "M": -0.5,
    "N": 0.8413,
    "P": 0.9772,
    "Q": 0.9987,
    "Z": -1.0,
}

QUALIFIER_CODES = set(
    (
        #
        # May be modified by SHEFPARM file
        #
        "B",  # Bad, Manual QC
        "D",  # Partial (qual = 4) – A 24 hour period was missing because 1 to 3 of the 6 hour periods was missing. The 24 hour amount is estimated using available/estimated 6 hour periods.
        "E",  # Estimated (qual = 5)
        "F",  # Flagged (qual = 1) – Flagged by sensor or telemetry (parity errors, for example)
        "G",  # Good, Manual QC
        "L",  # Lumped (qual = 6) - Estimated from the gages that have 6 hourly data with the constraint that the sum of the four 6 hourly periods is equal to the 24 hour amount.
        "M",  # Manual Edit
        "N",  # Reserved
        "P",  # Passed Level1, Level2, Level3
        "Q",  # Questioned in Level2, Level3 (qual = 3)
        "R",  # Rejected by Level1
        "S",  # Screened Level1 (qual = 0)(data value tested using preliminary criteria)
        "T",  # Triggered (tells database to start some additional function)
        "V",  # Verified Level1, Level2 (qual = 8)(data value verified using a more rigorous method)
        "W",  # Withheld (qual = 2) – The precipitation amount was manually input by the user (the measured precipitation was withheld).
        "Z",  # No QC Performed (null character)
    )
)

# Level1 = validity checks (i.e. range checking)
# Level2 = internal and temporal consistency checks (i.e. rate of change checks)
# Level3 = spatial consistency checks (e.g. temperature and precipitation field outliers)

DEFAULT_DURATION_CODES = {
    #
    # May not be modified by SHEFPARM file
    #
    # Default durations for PE codes that have default durations other than I
    #
    "AT": "D",
    "AU": "D",
    "AW": "D",
    "EA": "D",
    "EM": "D",
    "EP": "D",
    "ER": "D",
    "ET": "D",
    "EV": "D",
    "LC": "D",
    "PP": "D",
    "PR": "D",
    "QC": "D",
    "QV": "D",
    "RI": "D",
    "RP": "D",
    "RT": "D",
    "SF": "D",
    "TC": "S",
    "TF": "S",
    "TH": "S",
    "UC": "D",
    "UL": "D",
    "XG": "J",
    "XP": "Q",
}

DURATION_VARIABLE_CODES = {
    #
    # Not modified by SHEFPARM file
    #
    # Base numeric duration values for durtions specified with DVnxx
    #
    "S": 7000,
    "N": 0,
    "H": 1000,
    "D": 2000,
    "M": 3000,
    "Y": 4000,
}

TZ_NAMES = {
    #
    # Not modified by SHEFPARM file
    #
    "J": "PRC",  # China
    "HS": "US/Hawaii",  # Hawaiian standard
    "HD": "US/Hawaii",  # Hawaiian daylight
    "H": "US/Hawaii",  # Hawaiian local
    "BS": "Etc/GMT+11",  # Bering standard       (obsolete, Aleutian Islands now use US/Alaska)
    "BD": "Etc/GMT+10",  # Bering daylight       (obsolete, Aleutian Islands now use US/Alaska)
    "B": "Pacific/Midway",  # Bering local          (obsolete, Aleutian Islands now use US/Alaska)
    "LS": "Etc/GMT+9",  # Alaskan standard
    "LD": "Etc/GMT+8",  # Alaskan daylight
    "L": "US/Alaska",  # Alaskan local
    "YS": "Etc/GMT+8",  # Yukon standard        (--shefit_times gives bad times always)
    "YD": "Etc/GMT+7",  # Yukon daylight        (--shefit_times gives bad times always)
    "Y": "Canada/Yukon",  # Yukon local           (--shefit_times gives bad times always)
    "PS": "Etc/GMT+8",  # Pacific standard
    "PD": "Etc/GMT+7",  # Pacific daylight
    "P": "US/Pacific",  # Pacific local
    "MS": "Etc/GMT+7",  # Mountain standard
    "MD": "Etc/GMT+6",  # Mountain daylight
    "M": "US/Mountain",  # Mountain local
    "CS": "Etc/GMT+6",  # Central standard
    "CD": "Etc/GMT+5",  # Central daylight
    "C": "US/Central",  # Central
    "ES": "Etc/GMT+5",  # Eastern standard
    "ED": "Etc/GMT+4",  # Eastern daylight
    "E": "US/Eastern",  # Eastern local
    "AS": "Etc/GMT+4",  # Atlantic standard
    "AD": "Etc/GMT+3",  # Atlantic daylight
    "A": "Canada/Atlantic",  # Atlantic local
    "NS": "timedelta(hours=-3, minutes=-30)",  # Newfoundland standard
    "ND": "timedelta(hours=-2, minutes=-30)",  # Newfoundland daylight (--shefit_times gives bad times always)
    "N": "Canada/Newfoundland",  # Newfoundland local    (--shefit_times gives bad times in summer)
    "Z": "UTC",
}  # Zulu

DST_DATES = (
    #
    # DOM of transition for winter->summer and summer->winter for years 1976-2040.
    # Before 2007, months are April/October, afterward months are March/November
    # Used only when time zone is a string.
    #
    (26, 31),
    (24, 30),
    (30, 29),
    (29, 28),
    (27, 26),
    (26, 25),
    (25, 31),
    (24, 30),
    (29, 28),
    (28, 27),
    (27, 26),
    (5, 25),
    (3, 30),
    (2, 29),
    (1, 28),
    (7, 27),
    (5, 25),
    (4, 31),
    (3, 30),
    (2, 29),
    (7, 27),
    (6, 26),
    (5, 25),
    (4, 31),
    (2, 29),
    (1, 28),
    (7, 27),
    (6, 26),
    (4, 31),
    (3, 30),
    (2, 29),
    (11, 4),
    (9, 2),
    (8, 1),
    (14, 7),
    (13, 6),
    (11, 4),
    (10, 3),
    (9, 2),
    (8, 1),
    (13, 6),
    (12, 5),
    (11, 4),
    (10, 3),
    (8, 1),
    (14, 7),
    (13, 6),
    (12, 5),
    (10, 3),
    (9, 2),
    (8, 1),
    (14, 7),
    (12, 5),
    (11, 4),
    (10, 3),
    (9, 2),
    (14, 7),
    (13, 6),
    (12, 5),
    (11, 4),
    (9, 2),
    (8, 1),
    (14, 7),
    (13, 6),
    (11, 4),
)

TZ_OFFSETS = {
    #
    # Time zone offsets in minutes from UTC.
    # Used only when time zone is a string.
    #
    "Z": 0,
    "N": 210,
    "NS": 210,
    "ND": 210,
    "A": 240,
    "AS": 240,
    "AD": 180,
    "E": 300,
    "ES": 300,
    "ED": 240,
    "C": 360,
    "CS": 360,
    "CD": 300,
    "M": 420,
    "MS": 420,
    "MD": 360,
    "P": 480,
    "PS": 480,
    "PD": 420,
    "Y": 540,
    "YS": 540,
    "YD": 480,
    "L": 540,
    "LS": 540,
    "LD": 480,
    "H": 600,
    "HS": 600,
    "HD": 600,
    "B": 660,
    "BS": 660,
    "BD": 600,
    "J": -480,
}
