name: pytest

on:
  push:
    branches: [cwbi-test]
    paths:
      - .github/workflows/cwbi-test-pytests.yml
      - '**.py'
  pull_request:
    branches: ['cwbi-test']
    paths:
      - .github/workflows/cwbi-test-pytests.yml
      - '**.py'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Build and Run; Test DAGS
        run: ./tests.sh
