name: pytest

on:
  push:
    branches: [develop]
  pull_request:
    branches: ['develop', 'stable']
  
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Build and Run; Test DAGS
        run: ./tests.sh